name: Backend CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Descargar repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install -r requirements/base.txt

      - name: Ejecutar tests
        run: |
          pytest